alter table department AUTO_INCREMENT = 1;
INSERT INTO department (name) VALUES ('Upper management');
INSERT INTO department (name) VALUES ('Administration and management');
INSERT INTO department (name) VALUES ('Human Resources');
INSERT INTO department (name) VALUES ('Procurement');
INSERT INTO department (name) VALUES ('Infrastructure');
INSERT INTO department (name) VALUES ('Architecture');
INSERT INTO department (name) VALUES ('Operations');
INSERT INTO department (name) VALUES ('Engineering');
INSERT INTO department (name) VALUES ('QA');
INSERT INTO department (name) VALUES ('Security');
INSERT INTO department (name) VALUES ('Customer Service');
INSERT INTO department (name) VALUES ('Legal');
INSERT INTO department (name) VALUES ('Finance');
INSERT INTO department (name) VALUES ('Accounting');
INSERT INTO department (name) VALUES ('Treasury');
INSERT INTO department (name) VALUES ('Marketing');
INSERT INTO department (name) VALUES ('Merchandising');
INSERT INTO department (name) VALUES ('Commercial');
INSERT INTO department (name) VALUES ('Purchasing');
INSERT INTO department (name) VALUES ('Logistics');
INSERT INTO department (name) VALUES ('Production');
INSERT INTO department (name) VALUES ('TBA');

alter table role AUTO_INCREMENT = 1;
INSERT INTO role (title,salary,department_id) VALUES ('Chief Information Officer (CIO)', 63439, 1);
INSERT INTO role (title,salary,department_id) VALUES ('IT Director', 42374, 1);
INSERT INTO role (title,salary,department_id) VALUES ('Chief Technology Officer (CTO)', 111556, 1);
INSERT INTO role (title,salary,department_id) VALUES ('Chief Information Security Officer (CISO)', 145658, 1);
INSERT INTO role (title,salary,department_id) VALUES ('IT manager', 108622, 2);
INSERT INTO role (title,salary,department_id) VALUES ('IT project manager', 71136, 2);
INSERT INTO role (title,salary,department_id) VALUES ('IT product manager', 119813, 2);
INSERT INTO role (title,salary,department_id) VALUES ('IT coordinator', 100660, 2);
INSERT INTO role (title,salary,department_id) VALUES ('Business analyst', 108859, 2);
INSERT INTO role (title,salary,department_id) VALUES ('Procurement manager', 82316, 4);
INSERT INTO role (title,salary,department_id) VALUES ('Procurement officer', 50005, 4);
INSERT INTO role (title,salary,department_id) VALUES ('Purchasing agent', 93079, 4);
INSERT INTO role (title,salary,department_id) VALUES ('Procurement analyst', 155379, 4);
INSERT INTO role (title,salary,department_id) VALUES ('Procurement specialist', 87656, 4);
INSERT INTO role (title,salary,department_id) VALUES ('Infrastructure manager', 62147, 5);
INSERT INTO role (title,salary,department_id) VALUES ('Infrastructure engineer', 137765, 5);
INSERT INTO role (title,salary,department_id) VALUES ('Database administrator (DBA)', 92386, 5);
INSERT INTO role (title,salary,department_id) VALUES ('Database engineer', 138634, 5);
INSERT INTO role (title,salary,department_id) VALUES ('Database architect', 131014, 5);
INSERT INTO role (title,salary,department_id) VALUES ('Database analyst', 79166, 5);
INSERT INTO role (title,salary,department_id) VALUES ('Database specialist', 92790, 5);
INSERT INTO role (title,salary,department_id) VALUES ('Network manager', 66454, 5);
INSERT INTO role (title,salary,department_id) VALUES ('Network engineer', 143897, 5);
INSERT INTO role (title,salary,department_id) VALUES ('Network administrator', 110127, 5);
INSERT INTO role (title,salary,department_id) VALUES ('Network architect', 83945, 5);
INSERT INTO role (title,salary,department_id) VALUES ('Network analyst', 54341, 5);
INSERT INTO role (title,salary,department_id) VALUES ('Network specialist', 109873, 5);
INSERT INTO role (title,salary,department_id) VALUES ('Chief enterprise architect', 101342, 6);
INSERT INTO role (title,salary,department_id) VALUES ('Enterprise architect', 142092, 6);
INSERT INTO role (title,salary,department_id) VALUES ('Systems architect', 121433, 6);
INSERT INTO role (title,salary,department_id) VALUES ('Systems engineer', 145892, 6);
INSERT INTO role (title,salary,department_id) VALUES ('Systems coordinator', 80160, 6);
INSERT INTO role (title,salary,department_id) VALUES ('Systems analyst', 53127, 6);
INSERT INTO role (title,salary,department_id) VALUES ('IT operations director', 115153, 7);
INSERT INTO role (title,salary,department_id) VALUES ('Sysadmin', 131385, 7);
INSERT INTO role (title,salary,department_id) VALUES ('Hardware technician', 151465, 7);
INSERT INTO role (title,salary,department_id) VALUES ('Support administrator', 78174, 7);
INSERT INTO role (title,salary,department_id) VALUES ('IT support specialist', 151472, 7);
INSERT INTO role (title,salary,department_id) VALUES ('Help desk technician', 112841, 7);
INSERT INTO role (title,salary,department_id) VALUES ('Desktop support specialist', 74788, 7);
INSERT INTO role (title,salary,department_id) VALUES ('Software development', 125416, 8);
INSERT INTO role (title,salary,department_id) VALUES ('Development manager', 117718, 8);
INSERT INTO role (title,salary,department_id) VALUES ('Full-stack developer', 52343, 8);
INSERT INTO role (title,salary,department_id) VALUES ('Back-end developer', 123560, 8);
INSERT INTO role (title,salary,department_id) VALUES ('Front-end developer', 50771, 8);
INSERT INTO role (title,salary,department_id) VALUES ('Software architect', 98176, 8);
INSERT INTO role (title,salary,department_id) VALUES ('IT QA manager', 53566, 9);
INSERT INTO role (title,salary,department_id) VALUES ('QA engineer', 63305, 9);
INSERT INTO role (title,salary,department_id) VALUES ('QA analyst', 120828, 9);
INSERT INTO role (title,salary,department_id) VALUES ('Software tester', 129226, 9);
INSERT INTO role (title,salary,department_id) VALUES ('Business applications', 123645, 9);
INSERT INTO role (title,salary,department_id) VALUES ('Business applications manager', 70546, 9);
INSERT INTO role (title,salary,department_id) VALUES ('Application developer', 71799, 9);
INSERT INTO role (title,salary,department_id) VALUES ('Application analyst', 112355, 9);
INSERT INTO role (title,salary,department_id) VALUES ('Information security manager', 61381, 10);
INSERT INTO role (title,salary,department_id) VALUES ('Information security engineer', 59838, 10);
INSERT INTO role (title,salary,department_id) VALUES ('Information security analyst', 80049, 10);
INSERT INTO role (title,salary,department_id) VALUES ('Cloud security architect', 60732, 10);
INSERT INTO role (title,salary,department_id) VALUES ('Application security administrator', 153515, 10);
INSERT INTO role (title,salary,department_id) VALUES ('Cybersecurity analyst', 50376, 10);
INSERT INTO role (title,salary,department_id) VALUES ('Cybersecurity specialist', 131338, 10);
INSERT INTO role (title,salary,department_id) VALUES ('Data security specialist', 95562, 10);
INSERT INTO role (title,salary,department_id) VALUES ('Business intelligence', 48795, 10);
INSERT INTO role (title,salary,department_id) VALUES ('Business Partner', 45852, 10);
INSERT INTO role (title,salary,department_id) VALUES ('IT Supervisor', 47289, 2);
INSERT INTO role (title,salary,department_id) VALUES ('SSRS Engineer', 0, 3);
INSERT INTO role (title,salary,department_id) VALUES ('Legal', 1, NULL);
INSERT INTO role (title,salary,department_id) VALUES ('Finance', 1, NULL);
INSERT INTO ROLE (TITLE,SALARY,DEPARTMENT_ID) VALUES ('Accounting', 1, NULL);
INSERT INTO ROLE (TITLE,SALARY,DEPARTMENT_ID) VALUES ('Treasury', 1, NULL);
INSERT INTO ROLE (TITLE,SALARY,DEPARTMENT_ID) VALUES ('Marketing', 1, NULL);
INSERT INTO ROLE (TITLE,SALARY,DEPARTMENT_ID) VALUES ('Merchandising', 1, NULL);
INSERT INTO ROLE (TITLE,SALARY,DEPARTMENT_ID) VALUES ('Commercial', 1, NULL);
INSERT INTO ROLE (TITLE,SALARY,DEPARTMENT_ID) VALUES ('Purchasing', 1, NULL);
INSERT INTO ROLE (TITLE,SALARY,DEPARTMENT_ID) VALUES ('Logistics', 1, NULL);
INSERT INTO ROLE (TITLE,SALARY,DEPARTMENT_ID) VALUES ('Production', 1, NULL);
INSERT INTO ROLE (TITLE,SALARY,DEPARTMENT_ID) VALUES ('Legal', 1, NULL);

alter table employee AUTO_INCREMENT = 1;
INSERT INTO  employee (first_name,last_name,role_id) VALUES ( 'Gustavo', 'Miller',7);
INSERT INTO  employee (first_name,last_name,role_id) VALUES ( 'Felipe', 'Farrell',20);
INSERT INTO  employee (first_name,last_name,role_id) VALUES ( 'Mirtha', 'Isabelle',43);
INSERT INTO  employee (first_name,last_name,role_id) VALUES ( 'Camelia', 'Blackburn',10);
INSERT INTO  employee (first_name,last_name,role_id) VALUES ( 'Jim', 'Yates',15);
INSERT INTO  employee (first_name,last_name,role_id) VALUES ( 'Andre', 'Haley',2);
INSERT INTO  employee (first_name,last_name,role_id) VALUES ( 'Andrew', 'Lewis',17);
INSERT INTO  employee (first_name,last_name,role_id) VALUES ( 'Anne', 'Salazar',2);
INSERT INTO  employee (first_name,last_name,role_id) VALUES ( 'Elva', 'Galindo',24);
INSERT INTO  employee (first_name,last_name,role_id) VALUES ( 'Benton', 'Lee',8);
INSERT INTO  employee (first_name,last_name,role_id) VALUES ( 'Randy', 'Lucero',17);
INSERT INTO  employee (first_name,last_name,role_id) VALUES ( 'Brian', 'Delgado',64);
INSERT INTO  employee (first_name,last_name,role_id) VALUES ( 'Bejamin', 'Atkinson',25);
INSERT INTO  employee (first_name,last_name,role_id) VALUES ( 'Tom', 'Middleton',65);
INSERT INTO  employee (first_name,last_name,role_id) VALUES ( 'Cheryl', 'Koch',17);
INSERT INTO  employee (first_name,last_name,role_id) VALUES ( 'Lori-Ann', 'Lara',31);
INSERT INTO  employee (first_name,last_name,role_id) VALUES ( 'Corey', 'Schneider',57);
INSERT INTO  employee (first_name,last_name,role_id) VALUES ( 'Winnifred', 'Woodard',64);
INSERT INTO  employee (first_name,last_name,role_id) VALUES ( 'Dale', 'Peters',46);
INSERT INTO  employee (first_name,last_name,role_id) VALUES ( 'David', 'Bejamin',47);
INSERT INTO  employee (first_name,last_name,role_id) VALUES ( 'David', 'Richmond',37);
INSERT INTO  employee (first_name,last_name,role_id) VALUES ( 'Diane', 'Gregory',42);
INSERT INTO  employee (first_name,last_name,role_id) VALUES ( 'Dave', 'Hayden',53);
INSERT INTO  employee (first_name,last_name,role_id) VALUES ( 'Donna', 'Thompson',14);
INSERT INTO  employee (first_name,last_name,role_id) VALUES ( 'Ernie', 'Meadows',4);
INSERT INTO  employee (first_name,last_name,role_id) VALUES ( 'Erik', 'Bowen',62);
INSERT INTO  employee (first_name,last_name,role_id) VALUES ( 'Esther', 'Norton',60);
INSERT INTO  employee (first_name,last_name,role_id) VALUES ( 'Fred', 'Salas',21);
INSERT INTO  employee (first_name,last_name,role_id) VALUES ( 'Geoff', 'Waters',44);
INSERT INTO  employee (first_name,last_name,role_id) VALUES ( 'Gretha', 'McKee',37);
INSERT INTO  employee (first_name,last_name,role_id) VALUES ( 'Glenn', 'Sellers',16);
INSERT INTO  employee (first_name,last_name,role_id) VALUES ( 'Hilary', 'Brady',58);
INSERT INTO  employee (first_name,last_name,role_id) VALUES ( 'Joshua', 'Xiomara',52);
INSERT INTO  employee (first_name,last_name,role_id) VALUES ( 'Hannah', 'Walters',9);
INSERT INTO  employee (first_name,last_name,role_id) VALUES ( 'Heidi', 'Jamir',47);
INSERT INTO  employee (first_name,last_name,role_id) VALUES ( 'Randy', 'Mara',59);
INSERT INTO  employee (first_name,last_name,role_id) VALUES ( 'Isabelle', 'Jagger',35);
INSERT INTO  employee (first_name,last_name,role_id) VALUES ( 'Isaiah', 'Colten',51);
INSERT INTO  employee (first_name,last_name,role_id) VALUES ( 'Jessica', 'Burgess',37);
INSERT INTO  employee (first_name,last_name,role_id) VALUES ( 'John', 'Maxwell',27);
INSERT INTO  employee (first_name,last_name,role_id) VALUES ( 'Jim', 'Daniela',1);
INSERT INTO  employee (first_name,last_name,role_id) VALUES ( 'Jim', 'Delaney',50);
INSERT INTO  employee (first_name,last_name,role_id) VALUES ( 'James', 'Tanner',10);
INSERT INTO  employee (first_name,last_name,role_id) VALUES ( 'Jody', 'Ponce',31);
INSERT INTO  employee (first_name,last_name,role_id) VALUES ( 'John', 'Kennedy',60);
INSERT INTO  employee (first_name,last_name,role_id) VALUES ( 'John', 'Payne',40);
INSERT INTO  employee (first_name,last_name,role_id) VALUES ( 'John', 'Xiomara',23);
INSERT INTO  employee (first_name,last_name,role_id) VALUES ( 'Jonathan', 'Blankenship',38);
INSERT INTO  employee (first_name,last_name,role_id) VALUES ( 'Julie', 'Kennedy',36);
INSERT INTO  employee (first_name,last_name,role_id) VALUES ( 'Julie', 'Langston',29);
INSERT INTO  employee (first_name,last_name,role_id) VALUES ( 'Julie', 'Jennings',52);

SET SQL_SAFE_UPDATES = 0;
update employee set manager_id=1 where first_name= 'Jim' and last_name= 'Yates';
update employee set manager_id=1 where first_name= 'Jim' and last_name= 'Daniela';
update employee set manager_id=1 where first_name= 'Jim' and last_name= 'Delaney ';
update employee set manager_id=1 where first_name= 'Jody' and last_name= 'Ponce';
update employee set manager_id=5 where first_name= 'Mirtha' and last_name= 'Isabelle';
update employee set manager_id=5 where first_name= 'Cheryl' and last_name= 'Koch';
update employee set manager_id=5 where first_name= 'Corey' and last_name= 'Schneider';
update employee set manager_id=5 where first_name= 'Isabelle' and last_name= 'Jagger ';
update employee set manager_id=5 where first_name= 'Isaiah' and last_name= 'Colten ';
update employee set manager_id=22 where first_name= 'David' and last_name= 'Richmond';
update employee set manager_id=22 where first_name= 'Diane' and last_name= 'Gregory';
update employee set manager_id=22 where first_name= 'Dave' and last_name= 'Hayden';
update employee set manager_id=22 where first_name= 'Donna' and last_name= 'Thompson';
update employee set manager_id=22 where first_name= 'Hilary' and last_name= 'Brady';
update employee set manager_id=22 where first_name= 'Hannah' and last_name= 'Walters';
update employee set manager_id=43 where first_name= 'Felipe' and last_name= 'Farrell';
update employee set manager_id=43 where first_name= 'Andre' and last_name= 'Haley';
update employee set manager_id=43 where first_name= 'Andrew' and last_name= 'Lewis';
update employee set manager_id=43 where first_name= 'Anne' and last_name= 'Salazar';
update employee set manager_id=43 where first_name= 'Joshua' and last_name= 'Xiomara ';
update employee set manager_id=43 where first_name= 'Jessica' and last_name= 'Burgess';
update employee set manager_id=43 where first_name= 'John' and last_name= 'Maxwell ';
update employee set manager_id=43 where first_name= 'John' and last_name= 'Kennedy';
update employee set manager_id=43 where first_name= 'John' and last_name= 'Payne';
update employee set manager_id=43 where first_name= 'Julie' and last_name= 'Kennedy';
update employee set manager_id=43 where first_name= 'Julie' and last_name= 'Langston ';
update employee set manager_id=5 where first_name= 'Elva' and last_name= 'Galindo';
update employee set manager_id=5 where first_name= 'Brian' and last_name= 'Delgado';
update employee set manager_id=5 where first_name= 'Ernie' and last_name= 'Meadows';
update employee set manager_id=5 where first_name= 'Esther' and last_name= 'Norton';
update employee set manager_id=4 where first_name= 'Geoff' and last_name= 'Waters';
update employee set manager_id=4 where first_name= 'Gretha' and last_name= 'McKee';
update employee set manager_id=4 where first_name= 'Glenn' and last_name= 'Sellers';
